"""Add missing server schema columns

Revision ID: 013fcae77be0
Revises: 
Create Date: 2025-10-02 23:26:18.009170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '013fcae77be0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mcp_servers', 'server_type',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'generic'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mcp_servers', 'server_type',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'generic'::character varying"))
    # ### end Alembic commands ###
